'use strict';
// ── TASK POOL ─────────────────────────────────────────────────────
const POOL=[
  // MATHE (same numbers, no translation needed for the sum itself)
  {type:'mathe', q:'24 + 17 = ?', opts:['39','41','31','42'], ans:1},
  {type:'mathe', q:'8 × 7 = ?',   opts:['54','56','63','48'], ans:1},
  {type:'mathe', q:'100 − 37 = ?',opts:['63','67','73','53'], ans:0},
  {type:'mathe', q:'52 − 28 = ?', opts:['24','26','22','34'], ans:0},
  {type:'mathe', q:'6 × 9 = ?',   opts:['54','56','48','64'], ans:0},
  {type:'mathe', q:'200 − 78 = ?',opts:['122','132','118','128'],ans:0},

// LESEN
  {type:'lesen',
   de:{text:'Lisa geht jeden Tag mit ihrem Hund Bello in den Park. Heute hat Bello einen Stock gefunden und will ihn nicht mehr loslassen.',
       q:'Wie heißt Lisas Hund?', opts:['Rex','Bello','Max','Fifi']},
   ans:1},
  {type:'lesen',
   de:{text:'Im Herbst fallen die Blätter von den Bäumen. Viele Tiere bereiten sich auf den Winter vor. Der Igel sucht sich einen warmen Schlafplatz unter Laub.',
       q:'Was macht der Igel im Herbst?', opts:['Er spielt draußen','Er sucht einen Schlafplatz','Er fliegt in den Süden','Er baut ein Nest']},
   ans:1},
  {type:'lesen',
   de:{text:'Der Schmetterling beginnt sein Leben als Ei. Daraus wird eine Raupe, die sehr viel frisst. Dann verpuppt sie sich und verwandelt sich in einen wunderschönen Schmetterling.',
       q:'Was kommt nach der Raupe?', opts:['Ein Ei','Ein anderes Tier','Eine Puppe','Ein Schmetterling sofort']},
   ans:2},

  // SCHREIBEN
  {type:'schreiben',
   de:{prompt:'Schreibe 2–3 Sätze: Was ist dein Lieblingstier und warum magst du es?'},
   minChars:15},
  {type:'schreiben',
   de:{prompt:'Was hast du letzte Woche besonders Schönes erlebt? Beschreibe es kurz.'},
   minChars:15},
  {type:'schreiben',
   de:{prompt:'Was ist dein Lieblingsfach in der Schule und warum? Schreibe 2–3 Sätze.'},
   minChars:15},

  // MERKEN
  {type:'merken',
   de:{words:['🍎 Apfel','🐶 Hund','🌙 Mond','✏️ Bleistift','🏫 Schule'],
       q:'Welches Wort war NICHT in der Liste?', opts:['Apfel','Hund','Katze','Schule']},
   ans:2, showSecs:5},
  {type:'merken',
   de:{words:['🪟 Fenster','🐱 Katze','🌳 Baum','🪑 Stuhl','☁️ Wolke'],
       q:'Welches Wort war dabei?', opts:['Tisch','Katze','Buch','Lampe']},
   ans:1, showSecs:5},
// ── 50 NEUE FRAGEN ────────────────────────────────────────────────

  // MATHE – Rechnen & Geometrie
  {type:'mathe', q:'45 ÷ 9 = ?',   opts:['4','5','6','7'],        ans:1},
  {type:'mathe', q:'7 × 8 = ?',    opts:['54','56','63','49'],    ans:1},
  {type:'mathe', q:'3 × 3 × 3 = ?',opts:['9','18','27','36'],    ans:2},
  {type:'mathe', q:'1000 − 456 = ?',opts:['444','544','554','644'],ans:1},
  {type:'mathe', q:'125 + 368 = ?', opts:['483','493','503','513'],ans:1},
  {type:'mathe', q:'63 ÷ 7 = ?',   opts:['7','8','9','6'],        ans:2},
  {type:'mathe', q:'84 ÷ 2 = ?',   opts:['40','42','44','46'],    ans:1},
  {type:'mathe', q:'4 × 25 = ?',   opts:['80','90','100','110'],  ans:2},
  {type:'mathe', q:'15 × 6 = ?',   opts:['80','85','90','95'],    ans:2},
  {type:'mathe', q:'9 × 9 = ?',    opts:['72','81','90','99'],    ans:1},
  {type:'mathe', q:'300 − 145 = ?', opts:['145','155','165','175'],ans:1},
  {type:'mathe', q:'35 + 48 + 12 = ?',opts:['85','90','95','100'],ans:2},

  // NATUR & WISSENSCHAFT
  {type:'lesen',
   de:{text:'Wasser kann in drei verschiedenen Zuständen vorkommen: flüssig (Wasser), fest (Eis) und gasförmig (Wasserdampf). Wenn Wasser gefriert, wird es zu Eis.',
       q:'In welchem Zustand ist Wasser, wenn es gefriert?', opts:['Flüssig','Fest','Gasförmig','Nass']},
   ans:1},
  {type:'lesen',
   de:{text:'Pflanzen stellen ihre Nahrung selbst her. Dafür brauchen sie Sonnenlicht, Wasser und Kohlendioxid aus der Luft. Dieser Vorgang heißt Fotosynthese.',
       q:'Was brauchen Pflanzen NICHT für die Fotosynthese?', opts:['Sonnenlicht','Erde','Wasser','Kohlendioxid']},
   ans:1},
  {type:'lesen',
   de:{text:'Unser Sonnensystem besteht aus der Sonne und acht Planeten. Die Erde ist der dritte Planet von der Sonne. Der größte Planet ist Jupiter.',
       q:'Wie viele Planeten hat unser Sonnensystem?', opts:['7','8','9','10']},
   ans:1},
  {type:'lesen',
   de:{text:'In der Natur gibt es Nahrungsketten. Pflanzen werden von Pflanzenfressern gegessen, die dann von Fleischfressern gefressen werden. Zum Beispiel: Gras → Kaninchen → Fuchs.',
       q:'Was frisst in dieser Kette das Kaninchen?', opts:['Fuchs','Gras','Wasser','Insekten']},
   ans:1},
  {type:'lesen',
   de:{text:'Säugetiere sind warmblütig, haben Fell und ernähren ihre Jungen mit Muttermilch. Wale und Delfine sind trotz ihres Lebens im Wasser Säugetiere.',
       q:'Welches Tier ist KEIN Säugetier?', opts:['Wal','Delfin','Fledermaus','Krokodil']},
   ans:3},
  {type:'lesen',
   de:{text:'Die Schwerkraft zieht alle Objekte zur Erde. Sie gibt uns Gewicht und sorgt dafür, dass wir nicht davonfliegen. Der Mond hat eine geringere Schwerkraft als die Erde.',
       q:'Was bewirkt die Schwerkraft auf der Erde?', opts:['Sie macht uns leichter','Sie zieht uns zum Boden','Sie lässt uns fliegen','Sie erwärmt uns']},
   ans:1},
  {type:'lesen',
   de:{text:'Das menschliche Skelett besteht aus über 200 Knochen. Die Knochen schützen wichtige Organe, ermöglichen Bewegung und stützen den Körper.',
       q:'Wofür sind Knochen NICHT zuständig?', opts:['Schutz der Organe','Ermöglichen von Bewegung','Blut pumpen','Körper stützen']},
   ans:2},
  {type:'lesen',
   de:{text:'Die Erde dreht sich um die Sonne und ist dabei leicht geneigt. Diese Neigung sorgt dafür, dass wir Jahreszeiten haben. Im Sommer steht die Sonne höher am Himmel.',
       q:'Warum gibt es Jahreszeiten?', opts:['Weil es manchmal bewölkt ist','Wegen der Neigung der Erde','Weil die Sonne sich bewegt','Wegen des Mondes']},
   ans:1},
  {type:'lesen',
   de:{text:'Vulkane sind Öffnungen in der Erdkruste, durch die flüssiges Gestein (Magma) an die Oberfläche dringt. Sobald es ausbricht, nennt man es Lava.',
       q:'Wie heißt das flüssige Gestein NACHDEM es aus dem Vulkan austritt?', opts:['Magma','Lava','Granit','Basalt']},
   ans:1},
  {type:'lesen',
   de:{text:'Wasser verdunstet aus Meeren und Seen, steigt in die Luft, kühlt ab und bildet Wolken. Wenn die Wolken zu schwer werden, fällt das Wasser als Regen zurück.',
       q:'Woher kommt der Regen?', opts:['Aus den Bergen','Aus Wolken mit Wasser','Direkt aus dem Meer','Aus Flüssen']},
   ans:1},
  {type:'lesen',
   de:{text:'Insekten haben sechs Beine und einen dreiteiligen Körper: Kopf, Brust und Hinterleib. Spinnen sind KEINE Insekten – sie haben acht Beine.',
       q:'Wie viele Beine hat ein Insekt?', opts:['4','6','8','10']},
   ans:1},
  {type:'lesen',
   de:{text:'Licht bewegt sich rund 300.000 Kilometer pro Sekunde – das ist das Schnellste, was es gibt. Schall ist viel langsamer: Er legt etwa 343 Meter pro Sekunde zurück.',
       q:'Was ist schneller als Licht?', opts:['Schall','Wind','Nichts – Licht ist das Schnellste','Ein Flugzeug']},
   ans:2},
  {type:'lesen',
   de:{text:'Pflanzen nehmen Kohlendioxid auf und geben Sauerstoff ab. Das ist der Grund, warum Wälder so wichtig für unsere Luft sind. Der Amazonas-Regenwald wird oft als „Lunge der Erde" bezeichnet.',
       q:'Was geben Pflanzen an die Luft ab?', opts:['Kohlendioxid','Stickstoff','Sauerstoff','Wasserdampf']},
   ans:2},
  {type:'lesen',
   de:{text:'Viele Vögel ziehen im Herbst in wärmere Länder, weil es dort genug Nahrung gibt. Im Frühling kehren sie zurück. Schwalben fliegen dabei bis nach Afrika.',
       q:'Warum ziehen Vögel im Herbst in den Süden?', opts:['Weil sie die Sonne mögen','Weil es dort genug Nahrung gibt','Weil sie sich verirren','Wegen des Mondes']},
   ans:1},
  {type:'lesen',
   de:{text:'Recycling bedeutet, dass alte Materialien wiederverwertet werden. Papier, Glas, Plastik und Metall können recycelt werden. So schonen wir die Umwelt und sparen Energie.',
       q:'Was wird beim Recycling gemacht?', opts:['Müll verbrannt','Materialien wiederverwertet','Neue Rohstoffe gewonnen','Energie verschwendet']},
   ans:1},

  // ETHIK & SOZIALES
  {type:'lesen',
   de:{text:'In Lenas Klasse gibt es nur noch zwei Kuchenstücke, aber drei Kinder wollen welche. Lena schlägt vor, jeden gleich viel zu geben, auch wenn es weniger ist.',
       q:'Was macht Lenas Vorschlag gerecht?', opts:['Alle bekommen nichts','Alle bekommen gleich viel','Lena bekommt mehr','Der Stärkste bekommt alles']},
   ans:1},
  {type:'lesen',
   de:{text:'Tom sieht, dass sein Freund Jonas traurig ist, weil er beim Sport nicht mitmachen konnte. Tom setzt sich zu ihm und hört ihm zu, anstatt selbst zu spielen.',
       q:'Was zeigt Tom in dieser Situation?', opts:['Egoismus','Gleichgültigkeit','Mitgefühl','Angst']},
   ans:2},
  {type:'lesen',
   de:{text:'Im Straßenverkehr gibt es viele Regeln, zum Beispiel dass man bei Rot anhalten muss. Diese Regeln schützen alle Menschen. Ohne Regeln wäre es gefährlich.',
       q:'Warum gibt es Regeln im Straßenverkehr?', opts:['Damit die Polizei Arbeit hat','Zum Schutz aller Menschen','Damit Autos schneller fahren','Nur für Kinder']},
   ans:1},
  {type:'lesen',
   de:{text:'Als Anna krank ist, bringt ihre beste Freundin Mia ihr die Hausaufgaben nach Hause und spielt mit ihr. Freundschaft bedeutet, füreinander da zu sein.',
       q:'Was macht Mia zu einer guten Freundin?', opts:['Sie ist auch krank','Sie bringt die Hausaufgaben und kümmert sich','Sie macht Annas Hausaufgaben','Sie bleibt zuhause']},
   ans:1},
  {type:'lesen',
   de:{text:'Jeden Tag werden weltweit Wälder abgeholzt. Das zerstört den Lebensraum vieler Tiere. Jeder Mensch kann etwas tun, zum Beispiel Papier sparen oder Müll trennen.',
       q:'Was können wir tun, um Wälder zu schützen?', opts:['Mehr Papier benutzen','Papier sparen und Müll trennen','Mehr Holz kaufen','In den Wald fahren']},
   ans:1},
  {type:'lesen',
   de:{text:'Paul hat aus Versehen das Lieblingsspielzeug seines Bruders kaputt gemacht. Er überlegt, ob er die Wahrheit sagen oder so tun soll, als wäre es von selbst kaputt gegangen.',
       q:'Was sollte Paul tun?', opts:['Nichts sagen und hoffen','Die Wahrheit sagen und sich entschuldigen','Das Spielzeug verstecken','Die Schuld auf jemanden schieben']},
   ans:1},
  {type:'lesen',
   de:{text:'In Marlenes Klasse wird das neue Mädchen Sophie von einigen Kindern ausgelacht. Marlene findet das ungerecht und möchte etwas tun.',
       q:'Was wäre das Richtige für Marlene?', opts:['Auch mitmachen','Sophie trösten und die Lehrerin informieren','Wegsehen','Sophie woanders hinschicken']},
   ans:1},
  {type:'lesen',
   de:{text:'Kinder in der 3. Klasse haben Aufgaben in der Schule: Tafel wischen, Blumen gießen, Stühle hochstellen. Diese Aufgaben helfen der ganzen Klasse.',
       q:'Was lernst du durch Klassenaufgaben?', opts:['Dass Arbeit immer Spaß macht','Verantwortung für die Gemeinschaft','Dass Lehrer faul sind','Wie man Hausaufgaben vermeidet']},
   ans:1},

  // DEUTSCH
  {type:'lesen',
   de:{text:'In der deutschen Sprache haben Nomen einen Artikel. Der bestimmte Artikel lautet: der (männlich), die (weiblich) oder das (sächlich).',
       q:'Welchen Artikel hat das Nomen „Schule"?', opts:['der','die','das','ein']},
   ans:1},
  {type:'lesen',
   de:{text:'Im Deutschen bilden Nomen ihren Plural auf verschiedene Arten. Manchmal hängt man eine Endung an, manchmal ändert sich der Vokal.',
       q:'Wie lautet der Plural von „das Haus"?', opts:['die Hauser','die Häuser','die Haus','die Häuse']},
   ans:1},
  {type:'lesen',
   de:{text:'Verben sind Tunwörter – sie beschreiben eine Handlung. Nomen sind Namenwörter. Adjektive beschreiben Eigenschaften.',
       q:'Welches Wort ist ein Verb?', opts:['Schule','Blau','Rennen','Schnell']},
   ans:2},
  {type:'lesen',
   de:{text:'Ein Gegensatz (Antonym) ist ein Wort mit entgegengesetzter Bedeutung. Das Gegenteil von „groß" ist „klein". Das Gegenteil von „hell" ist „dunkel".',
       q:'Was ist das Gegenteil von „schnell"?', opts:['rasend','flink','langsam','eilig']},
   ans:2},
  {type:'lesen',
   de:{text:'Im Deutschen gibt es Aussagesätze (Punkt), Fragesätze (Fragezeichen) und Ausrufesätze (Ausrufezeichen).',
       q:'Womit endet ein Fragesatz?', opts:['Punkt','Komma','Fragezeichen','Ausrufezeichen']},
   ans:2},

  // ENGLISCH
  {type:'lesen',
   de:{text:'Farben auf Englisch: red (rot), blue (blau), green (grün), yellow (gelb), white (weiß), black (schwarz).',
       q:'Was bedeutet „green" auf Deutsch?', opts:['Gelb','Blau','Grün','Rot']},
   ans:2},
  {type:'lesen',
   de:{text:'Tiere auf Englisch: Hund = dog, Katze = cat, Pferd = horse, Vogel = bird, Fisch = fish.',
       q:'Was bedeutet „bird" auf Deutsch?', opts:['Bär','Vogel','Fisch','Hase']},
   ans:1},
  {type:'lesen',
   de:{text:'Die englischen Wochentage: Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday.',
       q:'Was bedeutet „Wednesday"?', opts:['Montag','Dienstag','Mittwoch','Donnerstag']},
   ans:2},
  {type:'lesen',
   de:{text:'Zahlen auf Englisch: one (1), two (2), three (3), four (4), five (5), six (6), seven (7), eight (8), nine (9), ten (10).',
       q:'Wie heißt die Zahl 7 auf Englisch?', opts:['six','eight','seven','five']},
   ans:2},
  {type:'lesen',
   de:{text:'"The cat is on the mat." – Übersetzt: Die Katze sitzt auf der Matte.',
       q:'Was sitzt auf der Matte?', opts:['Der Hund','Die Katze','Der Vogel','Die Maus']},
   ans:1},

  // MERKEN – weitere Wortlisten
  {type:'merken',
   de:{words:['📚 Buch','✏️ Bleistift','📐 Lineal','🖍️ Buntstift','📏 Zirkel'],
       q:'Welches Wort war NICHT in der Liste?', opts:['Buch','Radiergummi','Lineal','Bleistift']},
   ans:1, showSecs:5},
  {type:'merken',
   de:{words:['🔴 Rot','🔵 Blau','🟡 Gelb','🟢 Grün','🟣 Lila'],
       q:'Welche Farbe war in der Liste?', opts:['Orange','Braun','Lila','Weiß']},
   ans:2, showSecs:5},
  {type:'merken',
   de:{words:['🐘 Elefant','🦁 Löwe','🐧 Pinguin','🦊 Fuchs','🐬 Delfin'],
       q:'Welches Tier war NICHT dabei?', opts:['Elefant','Tiger','Pinguin','Fuchs']},
   ans:1, showSecs:5},
  {type:'merken',
   de:{words:['🍌 Banane','🍓 Erdbeere','🍊 Orange','🍇 Traube','🍉 Wassermelone'],
       q:'Welche Frucht war dabei?', opts:['Apfel','Pflaume','Traube','Kirsche']},
   ans:2, showSecs:5},
  {type:'merken',
   de:{words:['⚽ Fußball','🏊 Schwimmen','🎾 Tennis','🚴 Radfahren','🏀 Basketball'],
       q:'Welcher Sport war NICHT in der Liste?', opts:['Fußball','Schwimmen','Handball','Tennis']},
   ans:2, showSecs:5},
];